virtio-driver/virtio_blk: add DiscardWriteZeroesFlags struct
Clippy complains about the following assignment:

  error: boolean to int conversion using if
    --> virtio-driver/src/devices/virtio_blk.rs:89:21
     |
  89 |         let flags = if unmap { 1 } else { 0 };
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
               help: replace with from: `u32::from(unmap)`

Instead of using `u32::from(unmap)` as suggested, let's add a
bitflags structure to be used for other flags in the future.

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>